feedback/urls.py
from django.conf.urls import url

from . import views

app_name = 'feedback'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/answer/$', views.answer, name='answer'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^feedback/', include('feedback.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'', include('feedback.urls')),
]

feedback/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible

# Create your models here.

@python_2_unicode_compatible
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text

@python_2_unicode_compatible
class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.answer_text

feedback/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.shortcuts import redirect

from .models import Answer, Question


class IndexView(generic.ListView):
    template_name = 'feedback/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'feedback/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'feedback/results.html'

def answer(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_answer = question.answer_set.get(pk=request.POST['answer'])
    except (KeyError, Answer.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'feedback/detail.html', {
            'question': question,
            'error_message': "You didn't select an answer.",
        })
    else:
        selected_answer.votes += 1
        selected_answer.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('feedback:results', args=(question.id,)))
        

feedback/templates/feedback/detail.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'feedback/style.css' %}" />

<!-- <h1>{{ question.question_text }}</h1>
<ul>
{% for answer in question.answer_set.all %}
    <li>{{ answer.answer_text }}</li>
{% endfor %}
</ul> -->

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'feedback:answer' question.id %}" method="post">
{% csrf_token %}
{% for answer in question.answer_set.all %}
    <input type="radio" name="answer" id="answer{{ forloop.counter }}" value="{{ answer.id }}" />
    <label for="answer{{ forloop.counter }}">{{ answer.answer_text }}</label><br />
{% endfor %}
<input type="submit" value="Answer" />
</form>

feedback/templates/feedback/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'feedback/style.css' %}" />

<div class="container">
    <h3>Django Feedback</h3>

    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            <!-- <li><a href="/feedback/{{ question.id }}/">{{ question.question_text }}</a></li> -->
            <div class="question">
            <li><a href="{% url 'feedback:detail' question.id %}">{{ question.question_text }}</a></li>
            <form action="{% url 'feedback:answer' question.id %}" method="post">
            {% csrf_token %}
            {% for answer in question.answer_set.all %}
                <input type="radio" name="answer" id="answer{{ forloop.counter }}" value="{{ answer.id }}" />
                <label for="answer{{ forloop.counter }}">{{ answer.answer_text }}</label><br />
            {% endfor %}
            <input type="submit" value="Answer" />
            </form>
            </div>
        {% endfor %}
        </ul>
    {% else %}
        <p>No feedback is available.</p>
    {% endif %}
</div>

feedback/templates/feedback/results.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'feedback/style.css' %}" />

<h1>{{ question.question_text }}</h1>

<ul>
{% for answer in question.answer_set.all %}
    <li>{{ answer.answer_text }} -- {{ answer.votes }} vote{{ answer.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'feedback:detail' question.id %}">Change your answer?</a>